Update dq-check.yml

diff --git a/.github/workflows/dq-check.yml b/.github/workflows/dq-check.yml
--- a/.github/workflows/dq-check.yml
+++ b/.github/workflows/dq-check.yml
@@ -22,15 +22,21 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           pip install pylint
+          sudo apt-get install jq
+
+      - name: Debug: List files in lambda directory
+        run: |
+          ls -al aws/dev/lambda/
+          ls -al aws/dev/lambda/**/*.py
 
       - name: Run Pylint check on Python files
         run: |
-          pylint aws/dev/lambda/**/*.py --output-format=text > pylint_report.txt || true
+          pylint aws/dev/lambda/**/*.py --output-format=text > pylint_report.txt || echo "Pylint failed" >> pylint_report.txt
 
-      - name: Debug Print Pylint Report
+      - name: "Debug: Print Pylint Report"
         run: |
-          cat pylint_report.txt  # Show the full content of pylint_report.txt
-          
+          cat pylint_report.txt
+
       - name: Extract Pylint score and check
         run: |
           # Check if pylint_report.txt is empty
@@ -38,14 +44,14 @@ jobs:
             echo "Pylint report is empty. Skipping score extraction."
             exit 1
           fi
-          
+
           # Extract the last line of the report and get the score
           score_line=$(tail -n 1 pylint_report.txt)
           echo "Pylint Report Last Line: $score_line"
-          
+
           score=$(echo $score_line | grep -oP '\d+(\.\d+)?' | head -n 1)
           echo "Pylint Score: $score"
-          
+
           if ! [[ "$score" =~ ^[0-9]+(\.[0-9]+)?$ ]]; then
             echo "Invalid score: $score. Skipping check."
             exit 1
